// public class ExceptionHandling8
// {
//     public static void main(String[]args)  
//     {
//         System.out.println("Helloo");
//         try
//         {
//             System.out.println("try block");
//             System.out.println(10/0);
//         }
//         catch(Throwable e)
//         {
//             System.out.println("Exception Handled from catch");
//             System.out.println(10/0);
//         }
        
//         System.out.println("Byeee");
//     }  
// }
//! Output:-
//!Helloo
//!try block
//!Exception Handled from catch
//!Exception in thread "main" java.lang.ArithmeticException: / by zero 